[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "libra",
    "mercury",
]

[workspace.dependencies]
mercury = { path = "mercury" }

ahash = "0.8"
anyhow = "1.0"
axum = "0.8.4"
bincode = "2.0"
bstr = "1.0"
byte-unit = "5.0"
byteorder = "1.5"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "4.0"
colored = "3.0"
dashmap = "6.1"
encoding_rs = "0.8"
flate2 = "1.0"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
http = "1.0"
ignore = "0.4"
indicatif = "0.18"
lazy_static = "1.4"
libc = "0.2"
lru-mem = "0.3"
memchr = "2.0"
num_cpus = "1.0"
once_cell = "1.0"
pager = "0.16"
path-absolutize = "3.0"
pathdiff = "0.2"
quickcheck = "1.0"
rand = "0.9"
rand_chacha = "0.9"
rayon = "1.0"
regex = "1.0"
reqwest = "0.12.23"
ring = "0.17"
rpassword = "7.0"
scopeguard = "1.0"
sea-orm = "1.1.16"
serde = {  version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10"
similar = "2.0"
tempfile = "3.0"
serial_test = "3.0"
testcontainers = "0.25"
thiserror = "2.0"
threadpool = "1.0"
tokio = "1.0"
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.0"
uuid = "1.0"
walkdir = "2.0"
wax = "0.6"
zstd-sys = "2.0.15+zstd.1.5.7"
idgenerator = "2.0"
diffs = "0.5"

ceres = { git = "https://github.com/web3infra-foundation/mega.git", tag = "v0.0.7" }
common = { git = "https://github.com/web3infra-foundation/mega.git", tag = "v0.0.7" }
gemini = { git = "https://github.com/web3infra-foundation/mega.git", tag = "v0.0.7" }
neptune = { git = "https://github.com/web3infra-foundation/mega.git", tag = "v0.0.7" }
